try:
    a=2334/0
except Exception as e:
    print(e)
# else Gets eecuted when there is no error in the try block
else:
    print("hey i am good")

'''

'''